<h1 style="text-align:center; color:red;">Exercise XP</h1>

<h5 style="text-align:left; color:green;">Exercise 1 : Array Creation and Manipulation</h5>

In [8]:
import numpy as np

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h5 style="text-align:left; color:green;">Exercise 2 : Type Conversion and Array Operations</h5>

In [14]:
Liste = [3.14, 2.17, 0, 1, 2]
A = np.array(Liste)
A

array([3.14, 2.17, 0.  , 1.  , 2.  ])

<h5 style="text-align:left; color:green;">Exercise 3 : Working with Multi-Dimensional Arrays</h5>

In [24]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h5 style="text-align:left; color:green;">Exercise 4 : Creating Multi-Dimensional Array with Random Numbers</h5>

In [30]:
x = np.random.rand(4,5)
x = np.round(x,2)
x

array([[0.15, 0.87, 0.23, 0.22, 0.21],
       [0.85, 0.19, 1.  , 0.31, 0.02],
       [0.37, 0.93, 0.16, 0.57, 0.19],
       [0.56, 0.36, 0.24, 0.75, 0.36]])

<h5 style="text-align:left; color:green;">Exercise 5 : Indexing Arrays
</h5>

In [36]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row = array[1,:]

In [38]:
second_row

array([20, 21, 22, 23, 24])

<h5 style="text-align:left; color:green;">Exercise 6 : Reversing elements</h5>

In [45]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reverse_x = x[::-1]
reverse_x 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

<h5 style="text-align:left; color:green;">Exercise 7 : Identity Matrix</h5>

In [54]:
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<h5 style="text-align:left; color:green;">Exercise 8 : Simple Aggregate Funcs</h5>

In [62]:
x = np.arange(10)
Sum = np.sum(x)
Average = np.mean(x)
print(f"Somme : {Sum}, Moyenne : {Average}")

Somme : 45, Moyenne : 4.5


<h5 style="text-align:left; color:green;">Exercise 9 : Create Array and Change its Structure</h5>

In [72]:
x = np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

<h5 style="text-align:left; color:green;">Exercise 10 : Conditional Selection of Values</h5>

In [77]:
x = np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [79]:
x = np.arange(1,10)
odd_x=x[x%2==1]
odd_x

array([1, 3, 5, 7, 9])